apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook2-ui
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook2-ui
  template:
    metadata:
      labels:
        app: guestbook2-ui
    spec:
      containers:
      #- image: gcr.io/heptio-images/ks-guestbook-demo:0.2
      - image: public.ecr.aws/docker/library/httpd:latest
        name: guestbook2-ui
        ports:
        - containerPort: 80
