apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-testing-ui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app-testing-ui
  template:
    metadata:
      labels:
        app: app-testing-ui
    spec:
      containers:
      - image: public.ecr.aws/docker/library/httpd:latest
        name: app-testing-ui
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/apache2/htdocs/2-index.html
          subpath: index.html
      volumes:
      - name: config-volume
        configMap:
          name: app-testing-ui-cm
